# Generated by Django 5.1.1 on 2025-01-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGillo', '0004_workout_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='image',
        ),
    ]
