# Generated by Django 5.1.1 on 2025-01-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGillo', '0005_remove_workout_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fitness_goal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True),
        ),
    ]
