# Generated by Django 5.1.5 on 2025-01-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGillo', '0006_customer_fitness_goal_customer_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
