# Generated by Django 5.1.5 on 2025-01-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGillo', '0007_alter_workout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
