# Generated by Django 5.1.5 on 2025-01-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGillo', '0011_myworkout_delete_savedworkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyWorkout',
        ),
    ]
