# Generated by Django 5.1.5 on 2025-01-23 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGillo', '0012_delete_myworkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('current_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aim_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGillo.customer')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGillo.workout')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
