# Generated by Django 5.1.5 on 2025-01-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGillo', '0013_progress_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='description',
            field=models.TextField(blank=True, help_text="Add any notes or thoughts about today's progress", null=True),
        ),
    ]
