# Generated by Django 5.1.5 on 2025-01-23 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGillo', '0014_progress_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the meal plan', max_length=100)),
                ('calories', models.IntegerField(help_text='Total calories per day')),
                ('protein', models.DecimalField(decimal_places=2, help_text='Protein in grams', max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, help_text='Carbohydrates in grams', max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, help_text='Fats in grams', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGillo.customer')),
            ],
        ),
    ]
