# Generated by Django 5.1.5 on 2025-01-27 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGillo', '0015_mealplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGillo.workout')),
            ],
        ),
    ]
