# Generated by Django 5.1.5 on 2025-01-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGillo', '0016_myworkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
    ]
