# Generated by Django 5.1.5 on 2025-01-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGillo', '0017_workout_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the meal', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the meal', null=True)),
                ('calories', models.IntegerField(help_text='Calories for this meal')),
                ('protein', models.DecimalField(decimal_places=2, help_text='Protein in grams for this meal', max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, help_text='Carbohydrates in grams for this meal', max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, help_text='Fats in grams for this meal', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
