# Generated by Django 5.1.5 on 2025-01-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGillo', '0018_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='description',
        ),
    ]
