# Generated by Django 5.1.5 on 2025-01-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGillo', '0020_remove_mealplan_calories_remove_mealplan_carbs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='meals',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='calories',
            field=models.IntegerField(default=2000, help_text='Total calories per day'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Carbohydrates in grams', max_digits=5),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Fats in grams', max_digits=5),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Protein in grams', max_digits=5),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
