# Generated by Django 5.1.5 on 2025-01-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGillo', '0021_remove_mealplan_meals_mealplan_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='calories',
            field=models.IntegerField(help_text='Total calories per day'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='carbs',
            field=models.DecimalField(decimal_places=2, help_text='Carbohydrates in grams', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='fats',
            field=models.DecimalField(decimal_places=2, help_text='Fats in grams', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='protein',
            field=models.DecimalField(decimal_places=2, help_text='Protein in grams', max_digits=5),
        ),
    ]
